resources:
  repositories:
    - repository: pipeline-templates
      type: github
      name: lsportsltd/devops-pipeline-templates
      endpoint: lsportsltd
 
trigger: none

stages:
  - stage: PreBuild
    displayName: 'Pre-Build Setup'
    jobs:
      - job: HandleGitTag
        pool: k8s-agents-ci
        displayName: 'Handle Git Tag'
        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - script: |
              echo "Handling git tag before build..."
              VERSION=$(node -p "require('./package.json').version")
              TAG_NAME="trade360-nodejs-sdk-${VERSION}"
              
              # Always delete the tag if it exists (both local and remote) to allow template to recreate it
              echo "Checking for existing tag: $TAG_NAME"
              
              # Delete local tag if exists
              if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
                echo "Local tag $TAG_NAME exists, deleting..."
                git tag -d "$TAG_NAME" || true
              fi
              
              # Delete remote tag if exists (force delete)
              echo "Attempting to delete remote tag $TAG_NAME..."
              git push origin ":refs/tags/$TAG_NAME" 2>&1 || echo "Remote tag delete completed (may not have existed)"
              
              echo "Tag cleanup completed, template will create the tag"
            displayName: 'Clean Existing Tag'

  - template: general/generic-package-CICD.yaml@pipeline-templates
    parameters: 
      packageManager: 'npm'
      language: 'nodejs'
      languageVersion: '20'
      artifactImageLocation: '/usr/src/app/'
      serviceName: 'trade360_nodejs_sdk'
      group: trd
      domain: trade360-sdk
      product: stm
      team: guns-n-roses
      skipDeploy: "true"

  - stage: PublishToNPM
    displayName: 'Publish to NPM Registry'
    dependsOn: [PreBuild, BuildAndDeployPackage_trade360_nodejs_sdk]
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: PublishPackage
        pool: k8s-agents-ci
        displayName: 'Publish NPM Package'
        steps:
          - checkout: self
            persistCredentials: true
            clean: true

          - script: |
              echo "Handling git tag creation..."
              VERSION=$(node -p "require('./package.json').version")
              TAG_NAME="trade360-nodejs-sdk-${VERSION}"
              
              # Check if tag already exists
              if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
                echo "Tag $TAG_NAME already exists, skipping creation"
              else
                echo "Creating tag $TAG_NAME"
                git tag "$TAG_NAME"
                git push origin "$TAG_NAME" || echo "Failed to push tag, continuing..."
              fi
            displayName: 'Create Git Tag'

          - script: |
              echo "Starting NPM publish process..."
              
              # Get NPM token from SSM
              NPM_AUTOMATION_TOKEN=$(aws ssm get-parameter --name "/devopsr/npm/automation-token" --with-decryption --query "Parameter.Value" --output text)
              
              if [ -z "$NPM_AUTOMATION_TOKEN" ]; then
                echo "Error: NPM_AUTOMATION_TOKEN is empty"
                exit 1
              fi
              
              echo "Configuring NPM..."
              # Configure NPM authentication using automation token
              echo "//registry.npmjs.org/:_authToken=${NPM_AUTOMATION_TOKEN}" > ~/.npmrc
              echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
              
              echo "Setting up build environment..."
              # Ensure we're in the correct directory and files are in place
              pwd
              ls -la
              
              echo "Installing dependencies..."
              npm ci
              
              echo "Building package..."
              npm run build
              
              echo "Publishing to NPM..."
              npm publish --access public
              
              if [ $? -eq 0 ]; then
                echo "Successfully published to NPM"
                # Create the status file in the correct location
                mkdir -p /tmp/trade360-nodejs-sdk/app/dist
                touch /tmp/trade360-nodejs-sdk/app/dist/deploy_status_done_npm
              else
                echo "Failed to publish to NPM"
                exit 1
              fi
            displayName: 'Publish to NPM'
